# Introduction 

Econometrics is the art and science of learning from financial and economic data. It is an art as certainty stylised choices most be made when build an model and its estimation algorithm.  For instance, to we estimate the model using an analytical approach or using simulation.  It is a science of uncertainty and variation, a fact that sometimes can be lost on learners who prefer a cookbook approach to get YES/NO answers to probabilistic questions.  

This book will provide you with a overview of some of the important and emerging topics in econometrics.  In recent years, as computer-age technologies have advance in finance, we have seen as explosive in the use of computer-driven approaches financial research using ever more complex statistical algorithms. 

## A section

All chapter sections start with a second-level (`##`) or higher heading followed by your section title, like the sections above and below here. You can have as many as you want within a chapter.

### An unnumbered section {-}

Chapters and sections are numbered by default. To un-number a heading, add a `{.unnumbered}` or the shorter `{-}` at the end of the heading, like in this section.
